In [1]:
import numpy as np
import pandas as pd
from joblib import load

In [2]:
model=load('ava.save')

In [3]:
x_test=pd.read_csv(r'C:\Users\krishna\internship\Avalanche prediction project  in ML\datasets\x_test.csv')
y_test=pd.read_csv(r'C:\Users\krishna\internship\Avalanche prediction project  in ML\datasets\y_test.csv')

In [4]:
x_test=x_test.values
y_test=y_test.values

In [5]:
x_test

array([[  1.,   0.,  48.,  55.,  15.,  19.],
       [  0.,   0.,  26.,  12.,  -8.,  17.],
       [  1.,   0.,  61.,  17., -11.,   9.],
       [  1.,   0.,  80.,  73.,  14.,  35.],
       [  0.,   1.,  34.,  33.,  13.,  35.],
       [  0.,   0.,  50.,   5., -31.,   7.],
       [  1.,   0.,  34.,  76.,  -7.,  40.],
       [  1.,   0.,  27.,  61., -13.,  25.],
       [  0.,   1.,  34.,  59., -29.,   8.],
       [  1.,   0.,  59.,   6.,  10.,  37.],
       [  0.,   1.,  18.,  39.,  12.,   7.],
       [  0.,   0.,  55.,  24., -16.,  16.],
       [  1.,   0.,  66.,  78.,  -7.,  22.],
       [  1.,   0.,  22.,  13., -22.,  39.],
       [  0.,   0.,  55.,  24., -16.,  16.],
       [  1.,   0.,  34.,   4.,   3.,   9.],
       [  0.,   1.,  34.,  44.,   6.,   6.],
       [  0.,   1.,  34.,  33.,  13.,  35.],
       [  0.,   0.,  38.,   1., -14.,  31.],
       [  0.,   0.,  55.,  24., -16.,  16.],
       [  1.,   0.,  18.,  21., -11.,  23.],
       [  0.,   1.,  16.,  68.,  10.,  26.],
       [  

In [6]:
y_test

array([[2],
       [1],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [0],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [0],
       [2],
       [2],
       [1],
       [1],
       [2],
       [0],
       [0],
       [2],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1]], dtype=int64)

In [7]:
y_pred=model.predict(x_test)

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8536585365853658

In [9]:
from sklearn import metrics
metrics.confusion_matrix(y_test,y_pred)

array([[ 8,  0,  1],
       [ 0, 12,  1],
       [ 0,  4, 15]], dtype=int64)